---
name: PHP CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag Docker image
        run: |
          docker build -t php-docker-app .
          docker tag php-docker-app dhanshree111/php-docker-app:latest
      - name: Verify image is built locally
        run: docker images
      - name: Push Docker image to Docker Hub
        run: |
          docker push dhanshree111/php-docker-app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to Production Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.PRODUCTION_SERVER_IP }}
          username: ${{ secrets.PRODUCTION_SERVER_USER }}
          key: ${{ secrets.PRODUCTION_SERVER_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 15m
          script: |
           echo "Checking Docker and Docker Compose versions..."
           docker --version
           docker-compose --version

           echo "Navigating to the application directory..."
           cd /var/www/my-app

           echo "Stopping current containers..."
           docker-compose down || echo "No containers running, skipping."

           echo "Pulling new images from Docker Hub..."
           docker-compose pull

           echo "Starting containers..."
           docker-compose up -d --build

           echo "Checking running containers..."
           docker ps
