name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t php-docker-app .
          docker tag php-docker-app dhanshree111/php-docker-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push dhanshree111/php-docker-app:latest


  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: SSH to Production Server
         uses: appleboy/ssh-action@v0.1.3
         with:
           host: ${{ secrets.PRODUCTION_SERVER_IP }}
           username: ${{ secrets.PRODUCTION_SERVER_USER }}
           key: ${{ secrets.PRODUCTION_SERVER_SSH_KEY }}
           script: |
             cd /var/www/my-app
             git pull origin main
             docker-compose down
             docker-compose up -d --build
